#!/usr/bin/env node

const program = require('commander')
const { prompt } = require('inquirer')
require('dotenv').config()
const { sendMessage, sendBroadcast, sendFirstMessage } = require('./services/message')
const { autoLike } = require('./services/auto-like')
const { interval } = require('./services/utils')


const questions = [
    {
        type : 'input',
        name : 'id',
        message : 'Enter the id of the match:'
    },
    {
        type : 'input',
        name : 'message',
        message : 'Enter the message you want to send:'
    }
]

const questionsBroadcast = [
    {
        type : 'input',
        name : 'message',
        message : 'Enter the message you want to send:'
    }
]


program
    .version('0.1.0')
    .description('CLI for Tinder')

program
    .command('send:message')
    .alias('message')
    .description('Send a message to a match')
    .action(()=> {
        prompt(questions).then((answers)=> {
            sendMessage(answers.id, answers.message, (result)=> {
                    console.log(result)
            })
        })
    })


program
    .command('send:broadcast')
    .alias('broadcast')
    .description('Send a message to a match')
    .action(()=> {
        prompt(questionsBroadcast).then((answers)=> {
            sendBroadcast(answers.message)
        })
    })

program
    .command('send:first')
    .alias('first')
    .description('Send a first message just to new matches')
    .action(()=> {
        prompt(questionsBroadcast).then((answers)=> {
            sendFirstMessage(answers.message)
        })
    })

program
    .command('auto:likes [number]')
    .alias('likes')
    .description('Fetch profiles and autolike everyone of them')
    .action((number)=> {
        (number !== undefined) ? autoLike(number) : autoLike(10)
    })

program
    .command('test')
    .description('Test command')
    .action(()=> {
        interval(10, ()=> {
            console.log('Mihai')
        })
    })

program.parse(process.argv)
